#include <iostream>
#include <string>
#include <stdlib.h>
using namespace std;
void set_content_type(string content_type) 
{
  cout << "Content-type: " << content_type << "\r\n\r\n";
}

void set_page_title(string title) 
{
  cout << "<title>" << title << "</title>\n";
}

void bodyHtml()
{
cout << "<!doctype html>\n";
cout << "<html lang=\"en\">\n";
cout << "<head>\n";  
cout << "</head>\n";
cout<<"  <style>"
"body{"
"	margin: 0;"
"	padding: 0;"
"	background: #fff;"
"	/* font-family: 'Pacifico', cursive; */"
"	color: #fff;"
"	/* font-family: Arial; */"
"	font-family: 'Satisfy', cursive;"
"	font-size: 12px;"
"}"
".body{"
"	position: absolute;"
"	top: -20px;"
"	left: -20px;"
"	right: -40px;"
"	bottom: -40px;"
"	width: auto;"
"	height: auto;"
"    background: #b94007;"
"        background: -moz-linear-gradient(left, #f2306a 0%, #b94007 100%);"
"        background: -webkit-linear-gradient(left, #b94007 0%, #6d00a0 100%);"
"        background: linear-gradient(to right, #b94007 0%, #6d00a0 100%);"

"    filter: none;"
"	-webkit-filter: blur(5px);"
"	z-index: 0;   /* to  be researched*/"
"}"
""
".grad{"
"	position: absolute;"
"	top: -20px;"
"	left: -20px;"
"	right: -40px;"
"	bottom: -40px;"
"	width: auto;"
"	height: auto;"
"	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65)));" /* Chrome,Safari4+ */
"	z-index: 1;"
"	opacity: 0.7;"
"}"

".header{"
"	position: absolute;"
"	top: calc(50% - 35px);"
"	left: calc(50% - 255px);"
"	z-index: 2;"
"}"
""
".header div{"
"	float: left;"
"	color: #fff;"
"	font-family: 'Exo', sans-serif;"
"	font-size: 35px;"
"	font-weight: 200;"
"}"
""
".header div span{"
"	color: #1757ce !important;"
"	font-family: 'Satisfy', cursive;"
"}"

".login{"
"	position: absolute;"
"	top: calc(50% - 75px);"
"	left: calc(50% - 50px);"
"	height: 200px;"
"	width: 350px;"
"	padding: 10px;"
"	z-index: 2;"
"    "
"}"
".login input[type=int]{"
"	width: 250px;"
"	height: 30px;"
"	background: transparent;"
"	border: 1px solid rgba(255,255,255,0.6);"
"	border-radius: 2px;"
"	color: #fff;"
"	font-family: 'Exo', sans-serif;"
"	font-family: 'Pacifico', cursive;"
""
"	font-size: 16px;"
"	font-weight: 400;"
"	padding: 5px;"
"}"
""
".login input[type=text]{"
"	width: 250px;"
"	height: 30px;"
"	background: transparent;"
"	border: 1px solid rgba(255,255,255,0.6);"
"	border-radius: 2px;"
"	color: #fff;"
"	font-family: 'Exo', sans-serif;"
"	font-family: 'Pacifico', cursive;"
""
"	font-size: 16px;"
"	font-weight: 400;"
"	padding: 4px;"
"}"
""
".login input[type=password]{"
"	width: 250px;"
"	height: 30px;"
"	background: transparent;"
"	border: 1px solid rgba(255,255,255,0.6);"
"	border-radius: 2px;"
"	color: #fff;"
"	/* font-family: 'Exo', sans-serif; */"
"	font-family: 'Pacifico', cursive;"
""
"	font-size: 16px;"
"	font-weight: 400;"
"	padding: 4px;"
"	margin-top: 10px;"
"}"
""
".login input[type=submit]{"
"	width: 260px;"
"	height: 35px;"
"	background: #fff;"
"	border: 1px solid #fff;"
"	cursor: pointer;"
"	border-radius: 2px;"
"	color: #a18d6c;"
"	font-family: 'Exo', sans-serif;"
"	font-size: 16px;"
"	font-weight: 400;"
"	padding: 6px;"
"	margin-top: 10px;"
"}"
""
".login input[type=button]:hover{"
"	opacity: 0.8;"
"}"
""
".login input[type=button]:active{"
"	opacity: 0.6;"
"}"
""
".login input[type=text]:focus{"
"	outline: none;"
"	border: 1px solid rgba(255,255,255,0.9);"
"}"
""
".login input[type=password]:focus{"
"	outline: none;"
"	border: 1px solid rgba(255,255,255,0.9);"
"}"
""
".login input[type=button]:focus{"
"	outline: none;"
"}"

"::-webkit-input-placeholder{"
"   color: rgba(255,255,255,0.6);"
"}"
""
"::-moz-input-placeholder{"
"   color: rgba(255,255,255,0.6);"
"}"
"</style>";
  cout << "<body>\n";
  cout<<" "
    " <div class='body'></div>"
	"	<div class='grad'></div>"
	"	<div class='header'>"
	"		<div>Admin<span>Key</span></div>"
	"	</div>"
	"	<br>"
	"	<div class='login'>"
	"			<form method='POST' action='admin_login.php'>"
	"			<input type='int' placeholder='adhaar'  name='adhaar'required/>"
	"			<br>"
	"			<br>"
	"			<input type='text' placeholder='username' name='username' required/><br>"
	"			<input type='password' placeholder='password' name='password'required/><br>"
	"			<input type='submit' value='Login'>"
	"		</form>"
	"	</div>";
  cout << "</body>\n";
  cout << "</html>";
}
int main() {
  set_content_type("text/html"); 
  set_page_title("Admin's login");  
  bodyHtml();
  return 0;
}
   
  